# Generated by Django 2.1.7 on 2019-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191226_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
