# Generated by Django 2.1.7 on 2019-12-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191227_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo', to_field='user_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
